### ISSUE TITLE
Celeste Menu Texture Issues

### ISSUE THREAD

**Issue by rkr87** [JohnnyonFlame/FNAPatches#3]
Sorry if this isn't the correct repo to raise this, I wasn't sure where the correct place to raise it was.

![Capture](https://github.com/user-attachments/assets/6d5f2465-eeaf-4707-a7cf-81934d110fa3)

I recently got Celeste working in PortMaster on the Trimui Smart Pro, however, I am having some texture issues in menus, I've haven't progressed past the intro in game, but the textures while playing there do seem to be unaffected by the issues.

**Comment by JohnnyonFlame** [comment]
Hi, v3 doesn't have this problem, update.

**Comment by JohnnyonFlame** [comment]
By the way, I have a planned update to bring this to Portmaster finally, since permission has been given to redistribute FMOD.

**Comment by rkr87** [comment]
Awesome, can't wait for that!

Where can I find the updated V3 files? I got the version I have from a Google drive link posted on a guide 3-4 months ago.

**Comment by JohnnyonFlame** [comment]
> Awesome, can't wait for that!
> 
> Where can I find the updated V3 files? I got the version I have from a Google drive link posted on a guide 3-4 months ago.

Please check https://portmaster.games/detail.html?name=celeste for the updated Package and instructions.
